version: '3.8'
services:
  registry:
    image: registry:2
    container_name: private_registry
    ports:
      - "5000:5000"
    volumes:
      - ./data:/var/lib/registry
    networks:
      - registry
    restart: unless-stopped

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry_ui
    environment:
      - REGISTRY_TITLE=Private Docker Registry
      - NGINX_PROXY_PASS_URL=${REGISTRY_URL}
    networks:
      - registry
    restart: unless-stopped

networks:
  registry:
    external: true
